trigger:
- master

pr:
- master

variables:
  solutionPath: Trivia-API
  buildConfiguration: 'Release'
  sdkVersion: 3.1.x
  startupProjectPath: Trivia-API

stages: 

- stage: build
  pool:
    vmImage: ubuntu-latest

  jobs:

  - job: build

    steps:

    - task: UseDotNet@2
      displayName: dotnet sdk $(sdkVersion)
      inputs:
        packageType: 'sdk'
        version: '$(sdkVersion)'
        
        
    - script: dotnet restore
      displayName: dotnet restore
      workingDirectory: $(solutionPath)
      
    - script: dotnet build
       --configuration $(buildConfiguration)
       --no-restore
      displayName: dotnet build
      workingDirectory: $(solutionPath)
      
    - script: dotnet publish
        --configuration $(buildConfiguration)
        --output $(Build.ArtifactStagingDirectory)/app
      displayName: dotnet publish
      workingDirectory: $(startupProjectPath)

    - publish: $(Build.ArtifactStagingDirectory)/app
      artifact: app
      displayName: artifact publish app

- stage: deploy
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  dependsOn:
  - build
  pool:
    vmImage: ubuntu-latest

  jobs:

  - deployment: deploy_dev

    environment: dev

    strategy:
      runOnce:
        deploy:
          steps:

          - download: current
            artifact: app
            displayName: artifact download app

          - task: AzureRmWebAppDeployment@4
            displayName: azure app service deploy
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure subscription 1(282caa1f-eade-4353-b53b-23a39fbabd22)'
              appType: 'webApp'
              WebAppName: 'Trivia-API'
              packageForLinux: '$(Pipeline.Workspace)/app'