trigger:
- master

pr:
- master

variables:
  solutionPath: 'Trivia-API'
  buildConfiguration: 'Release'
  sdkVersion: 3.1.x
  startupProjectPath: Trivia-API

stages: 

- stage: build
  pool:
    vmImage: ubuntu-latest

  jobs:

  - job: build

    steps:

    - task: UseDotNet@2
      displayName: dotnet sdk $(sdkVersion)
      inputs:
        packageType: 'sdk'
        version: '$(sdkVersion)'
        
        
    - script: dotnet restore
      displayName: dotnet restore
      workingDirectory: $(solutionPath)
      
    - script: dotnet build
       --configuration $(buildConfiguration)
       --no-restore
      displayName: dotnet build
      workingDirectory: $(solutionPath)
      
    - script: dotnet publish
        --configuration $(buildConfiguration)
        --output $(Build.ArtifactStagingDirectory)/app
      displayName: dotnet publish
      workingDirectory: $(startupProjectPath)

    - publish: $(Build.ArtifactStagingDirectory)/app
      artifact: app
      displayName: artifact publish app  